### PR TITLE
Change \bibsstring → \bibstring (volume, edition, number)

### PR DESCRIPTION
**Pull request by AnadeB**
To allow abbreviate=false work correctly for volume, edition, number.

### CODE REVIEW

**Comment by AnadeB** [comment]
Do not omit (exact) date in the iso-authoryear bibliography format. It's required for online / broadcast sources.

**Comment by moewew** [comment]
I like the idea of using the generic `\bibstring` instead of the forced `\bibsstring`/`\biblstring` version, but I have no idea if the norm (or rather the stricter interpretation of the norm that this style follows) demands a specific form in some cases. The English version ISO 690:2010(E) I have access to does not seem to say this explicitly, but the examples could be seen as implying something like this.

The style also uses `\mainsstring` and `\mainlstring` (versions of `\bibsstring` and `\biblstring`, resp., in the main document language), maybe those could be unified as well?

---

The date handling in `iso-authoryear.bbx` could probably be overhauled even further.

https://github.com/michal-h21/biblatex-iso690/blob/270ea6733b14138d7bc9be6dec1e9838e8a49256/iso-authoryear.bbx#L8-L12

will already break down if people start using date ranges (`date = {2010/2012},`).  I'm thinking that what you are implementing comes down to `mergedate=basic` in the standard styles. Maybe it would be possible to lift even more code from there or, even better, to make use of the option directly.

**Comment by AnadeB** [comment]
Regarding the date, I'd rather see fixed it at least for simple dates ASAP. The Czech standard (ČSN ISO 690) demands the full date for (el. documents, newspapers, patents, TV broadcasts and similar), see interpretation, PDF, page 13, subsection 3.5.3, paragraph a:
https://docs.google.com/gview?url=http://www.citace.com/soubory/csniso690-interpretace.pdf

Regarding the full (non-abbreviated) strings in edition, the Czech standard says that it should be as is in the original document but can be abbreviated. Same PDF, page 12, 3.4a.
I'm not sure about the volume and number, though.

**Comment by moewew** [comment]
Given the substantial changes from https://github.com/michal-h21/biblatex-iso690/pull/74 were just merged, this PR probably needs some work before it can be merged.

As I commented before, I really like the idea of going from commands that explicitly force a particular form of the bibstring to the generic `\bibstring` as it gives users more control (via the `abbreviate` option), but I'm not sure how that squares with ISO requirements. @DavidLuptak any suggestion? It seems weird that the style uses all of `\bibstring`, `\bibsstring` and `\biblstring`.

**Comment by DavidLuptak** [comment]
The standard ISO 690 says about the abbreviations in general in its section 4.3 regarding these localisation strings:

> Generally accepted bibliographic terms should be abbreviated in accordance with the rules established in ISO 832.

I do not have ISO 832 at hand, but this standard might be the most beneficial for the creators of all biblatex localisation lbx files. For purposes of this style, I think we could go with the generic `\bibstring`s and `\mainlangbibstring`s, the previous forced short or long versions were mainly based on the examples that are not normative (only informative).

For the second part of this PR I created the separate issue #75.

PS: `ISO 832, Information and documentation — Bibliographic description and references — Rules for the abbreviation of bibliographic terms`

**Pull request merged**
