### PR TITLE
Multiple creators -- final name 'and' delimiter; first creator + et al.

### PR DESCRIPTION
**Pull request by DavidLuptak**
According to ISO 690:2011, following changes are required:
* as a rule of thumb, all of the creators' names should be given if possible. In the case any names are omitted, the norm exclusively states that

   > the name of the first creator shall be given followed by “and others” or “et al.”.

   Let's assume the threshold of `maxnames` option to be nine.
* I can not manage to find exclusively stated in the norm the second point about **_and_** delimiter before the final name in a name list, but all of the examples provided there show it in this way. Hence I propose this change here.

### CODE REVIEW

**Comment by DavidLuptak** [comment]
According to the examples provided in the text of the norm, there should be a comma before `et al.`.

**Comment by moewew** [comment]
Would you normally add a comma before the last element in a list consisting only of two items? "A, and B" looks a bit odd, I would say ("A, B, and C" less so). Since the "et" in "et al." is nothing more or less than an "and" I would not bother adding a comma before it.

But then I don't know the wording of the standard and can't comment about it with more detailed knowledge. It has been brought to my attention though that at least in some versions of the standard there is the caveat that the punctuation in the examples is to be seen as exemplary and does not form part of the standard itself.

**Comment by DavidLuptak** [comment]
Thank you @moewew for the reply, you are definitely right in this point of view in both cases you wrote about. I will correct it in this way and wait also for @michal-h21 input on this issue.

**Comment by johannesbottcher** [comment]
I skimmed the ISO from 2010 and sometimes they use a comma and sometimes they don't. Make sure you are consistent in your own references.

**Comment by DavidLuptak** [comment]
The case about comma before `et al.` in other implementations:
* Citace.com
  * citace.com's family styles **prints** comma
  * Slovak STN ISO 690 style **prints** comma
  * UTB [Univerzita Tomáše Bati ve Zlíne] style **does not print** comma
  * other csl-based styles **does not print** comma
* Zotero (csl-based) **does not print** comma
* Mendeley (csl-based) **does not print** comma
* RefWorks **prints** comma
* EndNote **prints** comma
* Petr Olsak's OPmac **prints** comma (looking in a history changelog, there is stated `Mar. 2016: et~al. -> , et~al. corrected.`
* etc.

Well, which option to choose, that's the question. I still propose the version without comma.

**Comment by michal-h21** [comment]
From grammatical point of view, there shouldn't be comma before "a" in Czech in this case. I can't find any rule for "et al",  but it seems that there should be no comma as well. I am not sure about other languages, but I suspect that this should be language dependent and don't know what would be the best way to implement it. Possibly as redefinition of localization strings in local language files?

**Comment by michal-h21** [comment]
It seems that comma before "et al" and final "and" is already language dependent, it is printed in English, but not in Czech, so it seems to be already included in the language files. 

There is also question whether it should be printed in the resource or document language. It is printed in the resource language now, as it was stated in interpretation of the older version. But that applied only to "et al", final "and" wasn't used. I think the document language should be used, as it is used in the examples. (It seems that the norm itself doesn't talk about final "and" at all. Of course. And of course, while Czech translation uses  "a" in the section 5.4, examples in the other sections are untranslated. Personally, I would prefer to not use it.)

**Comment by moewew** [comment]
For commas before "and" (some call it Oxford comma) `biblatex` has the command `\finalandcomma`. The `.lbx` files define this command to be either empty (`german`, `british`, ...) or to be a comma (`english` - `american`) so there either is no comma before an and or there is one *if* there are more than two items in the list - we never get to see a comma if there are only two items in the list. (That can of course be changed, if you want to use `\finalandcomma` for et al.)

**Comment by DavidLuptak** [comment]
@michal-h21 I am in. I have committed last commit to this pull request (I hope).
@moewew You are absolutely right.

**Comment by michal-h21** [comment]
@DavidLuptak thanks, it seems nice now. Maybe we should provide an option for people who want to use final "and", but that hasn't a  high priority. 

There is one last thing:

> For works with four or more creators, all names should be given if possible. If any names are omitted, the name of the first creator shall be given followed by “and others” or “et al.”. 

How can we find that any name was omitted? Or how can user specify it in the bib file?

**Comment by moewew** [comment]
Normally, `biblatex` "knows" that a name was omitted either if it truncated the names itself (because of `maxnames` settings and the like) or because the user used the "keyword" `and others` in the `.bib` file (as in `author = {Anne Elk and others}`)

**Comment by michal-h21** [comment]
@moewew I knew about `maxnames`, it used to be set to 5, according to the older norm, it is set to 9 now.  `and others` seems to do the trick, thanks!

**Pull request merged**
