### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by Kyslik**
So it looks nice on GitHub.

### CODE REVIEW

**Comment by Kyslik** [comment]
ups this is I guess same as #51 + renaming...

**Comment by michal-h21** [comment]
You are right, this is probably duplicate of #51, thank you anyway :)

**Comment by DavidLuptak** [comment]
@Kyslik, I have used your input in 62a53f922cc1912a0af3a4de8c53200eb141e70a. You can consider this pull request as a merged one, thank you very much for that!

**Comment by Kyslik** [comment]
@DavidLuptak thanks, looks nicer as advertised :)

č

**Pull request closed without merging**
