### PR TITLE
Initial bulgarian support

### PR DESCRIPTION
**Pull request by vgvassilev**
[iso-example-bg.pdf](https://github.com/michal-h21/biblatex-iso690/files/4007376/iso-example-bg.pdf)
This PR adds Bulgarian. I am not an expert by any chance in this field but I have received several requests in my personal repository.

Please let me know if I should change or adapt anything. It would help a lot of people if this becomes mainstream.

### CODE REVIEW

**Comment by moewew** [comment]
Note that `biblatex` has had a `bulgarian.lbx` since January 2017 (https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/bulgarian.lbx, https://github.com/plk/biblatex/issues/522). That implies that there should be no need to add a `bulgarian.lbx` to `biblatex-iso690`. To provide Bulgarian language support for `biblatex-iso690` it should only be necessary to supply a `bulgarian-iso.lbx`. (Even though it is theoretically possible for `biblatex-iso690` to bring its own version of `bulgarian.lbx` I ***strongly*** advise against that: Ideally one file should only be included in one LaTeX package/bundle and `<language>.lbx` files are always included in standard `biblatex`.)

**Comment by vgvassilev** [comment]
Thanks for the hints! It is great that the `bulgarian.lbx` finally landed. I have updated this PR correspondingly.

**Comment by DavidLuptak** [comment]
Thank you for your PR, it's nice to see an interest in other languages too..

I have some remarks for this PR:
* in `bulgarian-iso.lbx`, you define three keys:
  * `bibliography` looks the same as in the current `bulgarian.lbx` of `biblatex`, so there is no need to redefine it here,
  * `url` should be defined in `bulgarian.lbx` of `biblatex`,
  * `urlalso` looks that it follows the old version of localisation strings, I suggest to look at current strings of other languages,
* there are missing other localisation strings:
  * namely `at` and `bysupervisor`,
  * you can follow [translation guideline](https://github.com/michal-h21/biblatex-iso690/wiki/Translation-Guideline) to get idea about their meaning as well,
* you provide also example files to be merged in the master branch; examples are always good, but I would be against merging them into main branch, you can still put example files as an attachment to this PR.

Thank you for updating this PR and your contribution.

**Comment by vgvassilev** [comment]
I have made the suggested changes. Thanks for the hints.

I have a maybe unrelated question: in a bi-language setup using biber I need authors to be small caps:
```
% Print author names as small caps
\let\lastnameformat=\textsc
```
This does the trick for Bulgarian but not for English. Each bib entry has the corresponding `langid`.

**Comment by DavidLuptak** [comment]
I had to change some technicalities (bib strings are defined in form)
```
string = {{long version}{short version}}
```

Thanks once again for your contribution!

And regarding your question, changing small caps works for me, but maybe you could open new issue or something like that including [MWE](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that).

**Comment by vgvassilev** [comment]
Thanks a lot!

**Pull request merged**
