### PR TITLE
Add german translation for "online"

### PR DESCRIPTION
**Pull request by jendrikw**

### CODE REVIEW

**Comment by DavidLuptak** [comment]
Hey @jendrikw, thank you for this PR! Since there are more German localisations strings untranslated (see also #61), would you mind to look at the rest to have the [german-iso.lbx](https://github.com/michal-h21/biblatex-iso690/blob/master/german-iso.lbx) more complete? Thank you for your contribution and your response.

**Comment by jendrikw** [comment]
Sure, I'll do the rest as well. There are just a few details I'm unsure about.

Usage of `bydirector`: After searching for some time, I came to the conclusion that the director is usually referred to as *First Last (Regie)* or *Regie: First Last*, but not with a phrase like *directed by*. How can I handle this?

As you can see, we don't use the job title of the profession (which would be "Regisseur"), but the word "Regie", meaning "direction". Should I just put "Regie"?

`byinventor` basically has the same issue.

**Comment by DavidLuptak** [comment]
First, I forgot to mention the [translation guideline](https://github.com/michal-h21/biblatex-iso690/wiki/Translation-Guideline).

> Usage of `bydirector`: After searching for some time, I came to the conclusion that the director is usually referred to as _First Last (Regie)_ or _Regie: First Last_, but not with a phrase like _directed by_. How can I handle this?

This is handled by [biblatex](https://github.com/plk/biblatex/) itself, we don't modify this behaviour. Maybe we can think about it later, but both versions conform to the standard ISO 690 and we have chosen the default `biblatex` implementation.

> As you can see, we don't use the job title of the profession (which would be "Regisseur"), but the word "Regie", meaning "direction". Should I just put "Regie"?

This could be similar to other languages as well (see [translation matrix](https://github.com/michal-h21/biblatex-iso690/wiki/Translation-Guideline#translation-matrix)), where the `director` would be "Regisseur", and `directedby` would be something like "Regie". IMHO, the definition of "direction" has not so much common with the interpretation for our purposes.

You can see a different usage of [`director`](https://github.com/michal-h21/biblatex-iso690/blob/master/mybib.bib#L318) and [`directedby`](https://github.com/michal-h21/biblatex-iso690/blob/master/mybib.bib#L332) in the example bib file and then in [the documentation](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690.pdf#page=14).

**Comment by jendrikw** [comment]
Ok, thanks for the help.

**Comment by DavidLuptak** [comment]
@jendrikw :medal_sports: Thank you for your contribution! I am really glad we have this German localisation complete now.

**Pull request merged**
