### PR TITLE
Add missing bg translation.

### PR DESCRIPTION
**Pull request by vgvassilev**
I can translate `director` and `bydirector` if I know in what context they are used. I could not find this information on the internet.

### CODE REVIEW

**Comment by DavidLuptak** [comment]
The information are on the wiki page [Translation Guideline](https://github.com/michal-h21/biblatex-iso690/wiki/Translation-Guideline#the-key-director--bydirector). I have to add some example into bib file as well.

The example is
> Macbeth [film]. Directed by Orson WELLES. United States: Republic Pictures, 1948.

Now I consider adding `howpublished = {film}` as a bibstring as well, since this is only half-way done.

**Comment by vgvassilev** [comment]
I have translated the `director` and `bydirector`. Ping me if I should translate `film`...

**Comment by moewew** [comment]
Since the strings all use `\adddot` and not `\adddotspace` after abbreviations, there is no space between the abbreviation dot and the following word.
E.g.
```latex
\documentclass[bulgarian]{article}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=iso-authoryear, backend=biber]{biblatex}


\begin{filecontents}{\jobname.bib}
@thesis{luptak2016thesis,
  author       = {Lupták, Dávid},
  title        = {Typesetting of Bibliography According to ISO 690 Norm},
  date         = {2016},
  howpublished = {online},
  type         = {bathesis},
  institution  = {Masaryk University, Faculty of Informatics},
  location     = {Brno},
  supervisor   = {Petr Sojka},
  url          = {https://is.muni.cz/th/422640/fi_b/},
  urldate      = {2016-06-14},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\cite{luptak2016thesis}
\printbibliography
\end{document}
```
produces
>  ръков.от Petr SOJKA.

 Is that intended? Or should the correct output be
>  ръков. от Petr SOJKA.

**Comment by vgvassilev** [comment]
Good point. I will fix it in a sec.

**Comment by DavidLuptak** [comment]
I am so sorry I haven't replied earlier, could you please also translate `film`? Then we can merge this PR. Thank you so much!

**Comment by vgvassilev** [comment]
Done!

**Comment by DavidLuptak** [comment]
Thank you once again for swift response!

**Pull request merged**
